### ISSUE TITLE
 Error when Edit after Encoding (v5.7.4)

### ISSUE THREAD

**Issue by Hankuuuu** [cdgriffith/FastFlix#585] opened 2024-07-20 02:28 UTC
🤗 Thank you Chris again for the hard work. A minor bug, hope it helps.

![EditError](https://github.com/user-attachments/assets/a4429c30-5ea2-4213-851b-6daf231e8f01)

▶️
This issue occurs with **FastFlix_5.7.4_installer.exe**
It does not occur with the portablee **FastFlix_5.7.4_win64.zip** version.

▶️
After the error occurs, the software is unable to encode more videos until it is restarted. 
Alternatively, clicking on the Edit Icon **twice** can restore normal functionality. 
(after exploring various methods and finding this to be the quickest solution)

😁

.

**Comment by cdgriffith** [comment] 2024-08-06 01:37
Hi @Hankuuuu, I am trying to reproduce this and coming up short. Have you tried re-installing? 

As it's only the install version I have a gut feeling it might be due to FastFlix was running when the uninstall was run and not all files were updated. So please just make double sure FastFlix is closed before doing a manual uninstall, then new install. (I have done this many a time myself, need to find a way to check if FastFlix is running during the uninstall process)

**Comment by Hankuuuu** [comment] 2024-08-07 08:47
.
**💚 Thank you, Chris, for making the software perfect and wonderful.
👌 No problem. Here are the steps I followed for the testing:**


  .
  .
 1️⃣ I installed a brand new Windows 11 in VMware, and updated it to the latest 23H2 to ensure a clean environment:

![01](https://github.com/user-attachments/assets/63dba34c-6c1f-4146-a7c8-6ad153193ae9)


2️⃣ I also used "Iobit Uninstaller" to monitor the software installation, ensuring future removals are cleaner.

![02](https://github.com/user-attachments/assets/62f780e6-0935-44df-bfc7-6f6e73686152)



3️⃣ Iobit recorded all processes after installed Fastflix:

![03](https://github.com/user-attachments/assets/fbc738a3-01e2-4bb7-96fe-500349a1a810)



4️⃣  I downloaded the latest FFMpeg , imported a video, used the "Default", then started converting:

![04](https://github.com/user-attachments/assets/1b1f4681-2d07-47b3-a3cb-92084c036225)



5️⃣ Convert successful:

![05](https://github.com/user-attachments/assets/cb2bd796-e52d-4068-a664-993c887c8e44)



6️⃣ In the "Encoding Queue", I clicked "Edit", an error occurred, and it could no longer compile:

![06 2](https://github.com/user-attachments/assets/8b67e8d3-5ef1-49aa-a199-cf5b5d14a08c)

![06](https://github.com/user-attachments/assets/152ab0e6-8769-41b6-8a19-6a173ec489c3)



7️⃣ If I return to the UI and click "Edit Icon" again, it can be fixed and back to the Main:

![06 2](https://github.com/user-attachments/assets/8b67e8d3-5ef1-49aa-a199-cf5b5d14a08c)

![07](https://github.com/user-attachments/assets/629e9366-dea8-402b-bbc6-f83973b426c5)



8️⃣ Now, I uninstalled it. I used "Process Explorer" to ensure "FastFlix" was completely closed and not running in the background:

![08](https://github.com/user-attachments/assets/d16d8427-be54-43f3-a320-6b3c67313060)



9️⃣ After uninstalled,  "Iobit Uninstaller" popped up:

![09](https://github.com/user-attachments/assets/db2deac3-2788-4451-bdf8-a2ecdfe00c12)



🔟 It helped to completely remove all files, temporary, registry, and other data generated by FastFlix:

![10](https://github.com/user-attachments/assets/52dbfb94-700c-414f-afd1-cc3962b56ed6)



▶️ Rebooted system and reinstalled "FastFlix 5.7.4".

![11](https://github.com/user-attachments/assets/72aa0fc5-0cdb-4596-8d19-ae13c94da049)



▶️ Installed the latest FFMpeg again, imported a video, used the "Default", then started converting:

![12](https://github.com/user-attachments/assets/d7fcc660-c479-4d82-b1ae-13fe34c8ffe1)



▶️ The same error occurred in the software.

![13](https://github.com/user-attachments/assets/5c917ae5-48d1-4245-ad81-c32ecb9b9918)



▶️ Here are the suggestions from GPT (not necessarily correct, just for reference only):

![14](https://github.com/user-attachments/assets/7540cb8e-0eb3-4e58-af99-5b95eed37bf5)

**Comment by Hankuuuu** [comment] 2024-08-07 08:48
By the way, May I make a correction? 
Actually, both versions  **FastFlix_5.7.4_installer.exe**  and  **FastFlix_5.7.4_win64.zip portable**  have the same issue. 
After testing many videos, it seems the problem is that some videos ‘work’ and some ‘have errors':


.


![15](https://github.com/user-attachments/assets/2ef49f0c-37d1-44e9-b9d4-104ad0531141)

[The sample download here](https://www.dropbox.com/scl/fo/v86uh5dpzsh2kggcatsew/AB5orQ1_XZk8KxqvVJnWIqI?rlkey=60v9j4hae5o63ewu5c4vmbz16&st=ogdr7ed7&dl=0
) if you need.
(The videos converted from VideoStudio are larger because I no longer have this software, so they are the original ones. Please bear with me)

.

**Comment by cdgriffith** [comment] 2024-08-07 15:12
@Hankuuuu thank you so much for the details and example files! 

It turns out the error happens when a video file has the audio or subtitles tracks come first.  For example the Terminal Island one has it's video as the third track. 

This was an error in the FastFlix code when dealing with videos not as the first track, so I am fixing it for next version, thank you again for all the details!

**Comment by Hankuuuu** [comment] 2024-08-07 18:08
You are very welcome, Chris 👍

It's awesome that you figured out the cause and key points. 
I am so happy and can't wait for your next version. 😍

**Comment by cdgriffith** [comment] 2024-08-07 19:36
Should be fixed in 5.8.0, beta to test with: https://github.com/cdgriffith/FastFlix/releases/tag/5.8.0b0

**Comment by Hankuuuu** [comment] 2024-08-07 21:16
Great Job, Chris! 
It works now! 
Love it! 💚

**Closed** 2024-08-09 19:15 UTC
Labels: bug
