### ISSUE TITLE
Ubuntu 22 - App UI Interaction causing Ubuntu UI to crash and force user back to login, killing all running apps

### ISSUE THREAD

**Issue by x9sim9** [cdgriffith/FastFlix#399] opened 2022-12-21 23:23 UTC
Having an issue with Ubuntu 22 where interacting with the UI is causing the entire ubuntu desktop to crash and then being forced back to the login screen, this also kills all running apps.

Issue is pretty easy to recreate click on a drop down, while open click an empty area in the UI, happens with text boxes as well.

Strangely doesn't effect encoding at all just changing settings, but as profiles wont store resolution changes I have to manually type the desired resolution for each file, and this crashing issue makes a tedious process (having to do this on every file) even more so (by having to start again after logging back into ubuntu)

**Comment by cdgriffith** [comment] 2023-02-16 04:46
Just wanted to comment that I feel your pain now, I recently switched to Ubuntu and having the same issue myself. Kinda hard to trap that as soon as it's triggered everything dies and don't see how to catch it. This is going to be a fun one!

**Comment by cdgriffith** [comment] 2023-02-19 00:46
Asking in the QT forms https://forum.qt.io/topic/143081/selecting-outside-a-combobox-logs-out-the-user-and-crashes-desktop-on-ubuntu-22-04

**Comment by cdgriffith** [comment] 2023-03-07 04:40
Hey, I switched to some newer packages for the next version 5.2.0, and when it comes out should stop this crazy issues as a heads up!  Not sure the fix, but have stopped having the problem on my system.  (Also switched from AMD graphics card to Nvidia graphics card, so if it's still happening for you in the 5.2.0 branch please let me know!)

**Comment by x9sim9** [comment] 2023-03-07 07:35
Thanks Chris, will keep an eye out for it. very easy bug to recreate so should know pretty quickly if there is still an issue.

**Comment by anikdv** [comment] 2023-04-18 18:19
Unfortunately, the problem is still there on Ubuntu 22.04 with Wayland :)

**Comment by cdgriffith** [comment] 2023-04-20 01:48
Curious, what video card are you using and what graphics driver package?

**Comment by cdgriffith** [comment] 2023-04-20 02:09
Ah, well okay I don't think it's drivers after latest test. Does seem to be a Wayland specific issue, as I have the issue on either Nvidia or AMD graphics. I just apparently switched to X11 at some point (which it doesn't explode on)

**Comment by cdgriffith** [comment] 2023-04-20 02:13
Oh I just checked that QT thread and see there are updates (didn't get email notifications so totally missed them) 

https://wiki.qt.io/Qt_6.4_Known_Issues#Wayland

https://bugreports.qt.io/browse/QTBUG-107755

I don't know how update Mutter, but just running it with `QT_QPA_PLATFORM=xcb ./FastFlix` did fix it for me

**Comment by cdgriffith** [comment] 2023-04-27 14:01
Closing this as there is nothing possible to fix on FastFlix side that I know of. Just need to update Mutter or use the `xcb` QT platform as shown above.

**Closed by cdgriffith** 2023-04-27 14:01 UTC
Labels: FastFlix can't fix that
