### ISSUE TITLE
Multiple audio outputs from single track

### ISSUE THREAD

**Issue by chreds** [cdgriffith/FastFlix#408] opened 2023-02-10 23:17 UTC
Is there a way to have a single input track output two different formats. For example, the input video only has an ac3 5.1 track, but I'd like to output both a pass through and as a conversion to aac stereo (for compatibility). One option from a GUI perspective might be a be able to "duplicate" an audio track (which would maybe show indented under the parent track.

Thanks! I just found FastFlix today and it's saving me soooo much time vs Handbrake. I really appreciate the effort you're putting into it!

**Comment by cdgriffith** [comment] 2023-02-11 05:22
As long as you're using a ffmpeg encoder yes! (aka x265, x264, any non Rigaya one)

There is a clipboard icon at the far right of the audio track that if you click it will add a duplicate of it below that you can change the conversions for. If you have questions or issues using it let me know!

**Closed** 2023-03-09 03:08 UTC
Labels: question
