### ISSUE TITLE
SVT-AV1 replace 'QP' to 'CRF'

### ISSUE THREAD

**Issue by ShubhamVimal** [cdgriffith/FastFlix#515] opened 2023-08-13 07:25 UTC
**FastFlix Version:**
5.5.6

**Operating System:**
Windows 10 Pro x64

**Describe the bug**
Replace SVT-AV1 ' qp ' to use ' crf '. Official docs also says to use ' crf ', you can check it. I don't understand why are you still using 'qp' . In raw commands section -qp is used instead -crf. Correct it as soon as possible, please. 

**Screenshots**
![Inkedgui_preview](https://github.com/cdgriffith/FastFlix/assets/51742764/26c9dcb2-bcef-48a6-96ad-fcd9f8937b93)

**Comment by cdgriffith** [comment] 2023-08-14 16:48
Duplicate of https://github.com/cdgriffith/FastFlix/issues/503 

Don't have time to work on it for a while. Always accepting PRs.

**Closed by cdgriffith** 2023-08-14 16:48 UTC
Labels: bug
